<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c45c64cf-3e93-40b8-967a-b5c53b364406</elementGuidId>
    <imagePath></imagePath>
    <name>link_sortOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sort-buttons__element"]:nth-child(${link_sortOptions_nthChild}) &gt; [class="sort-buttons__link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#') and equals(@text,'By price')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="${link_sortOptions_internalRoleLinkName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>a36756ed-b9af-48f5-bbb6-dcfa3796d14a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>By price</value>
        <webElementGuid>a36756ed-b9af-48f5-bbb6-dcfa3796d14a</webElementGuid>
    </webElementProperties>
</WebElementEntity>