<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6a7d44df-5485-4f01-9e8f-40ab322644b9</elementGuidId>
    <imagePath></imagePath>
    <name>button_RemoveItem</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[5]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="cart-item\ row"]:nth-child(4) [class="btn\ btn-sm\ btn-outline-secondary"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Remove')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Remove"i] &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Remove</value>
        <webElementGuid>a36756ed-b9af-48f5-bbb6-dcfa3796d14a</webElementGuid>
    </webElementProperties>
</WebElementEntity>